# netlify.toml
[build]
  command = "CI=false npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../package-lock.json"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.9.2"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"